### ISSUE TITLE
私自统计账号密码！

### ISSUE THREAD

**Issue by idootop** [52fisher/wenkuDown#1]
私自统计别人的账号密码和下载文档的信息可还行，呵呵

**Comment by 52fisher** [comment]
希望先看一下 README.md当中的警告内容

> 本脚本为非官方脚本，由于官网与百度文库的协议存在跨域问题，所以使用了url转发作为两者沟通的桥梁，在此过程中保证不保存任何用户的信息，介意者勿用。

针对此疑问，在发布此项目之前已经与网站官方进行联系，且获取了同意。同时就官网协议存在跨域问题也进行了反馈。统计这些账号信息对我来说没有任何用处，因为我不需要从中获利。

**Comment by 52fisher** [comment]
> 
> 
> 私自统计别人的账号密码和下载文档的信息可还行，呵呵

希望先看一下 README.md当中的警告内容

> 本脚本为非官方脚本，由于官网与百度文库的协议存在跨域问题，所以使用了url转发作为两者沟通的桥梁，在此过程中保证不保存任何用户的信息，介意者勿用。

针对此疑问，在发布此项目之前已经与网站官方进行联系，且获取了同意。同时就官网协议存在跨域问题也进行了反馈。统计这些账号信息对我来说没有任何用处，因为我不需要从中获利。

**Comment by idootop** [comment]
好吧，我的锅没细看readme直接看的代码，向你道歉。
